name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

template: |
  $CHANGES

  **Full Changelog**: [$PREVIOUS_TAG...$RESOLVED_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION)
